import type { Product } from "@/lib/cart-context";

export const CATEGORIES = [
  "All Products",
  "SaaS",
  "Support",
  "Hosting",
  "Add-ons",
];

export const PRODUCT_TYPES: Record<string, string> = {
  SERVICE: "Service",
  CONSUMABLE: "Consumable (Goods)",
  STORABLE: "Storable (Goods)",
};

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Subly Pro",
    category: "SaaS",
    type: "SERVICE",
    description:
      "Full-featured subscription management with analytics, automation, and priority support. Best for growing teams that need powerful tooling.",
    salesPrice: 1200,
    monthlyPrice: 1200,
    yearlyPrice: 12000,
    costPrice: 600,
    rating: 4.8,
    tag: "Popular",
    taxRate: 15,
    variants: [
      { attribute: "Brand", value: "Odoo", extraPrice: 560 },
      { attribute: "Brand", value: "Standard", extraPrice: 0 },
      { attribute: "Tier", value: "Enterprise", extraPrice: 300 },
      { attribute: "Tier", value: "Professional", extraPrice: 100 },
    ],
    images: ["img1", "img2", "img3"],
    recurringPlan: {
      name: "Pro Monthly",
      billingPeriod: "MONTHLY",
      price: 1200,
      minimumQuantity: 1,
      autoClose: false,
      closeable: true,
      renewable: true,
      pausable: true,
    },
  },
  {
    id: "2",
    name: "Subly Starter",
    category: "SaaS",
    type: "SERVICE",
    description:
      "Get started with core subscription features. Ideal for solopreneurs and small businesses looking for simplicity.",
    salesPrice: 499,
    monthlyPrice: 499,
    yearlyPrice: 4990,
    costPrice: 200,
    rating: 4.5,
    tag: null,
    taxRate: 15,
    variants: [
      { attribute: "Brand", value: "Odoo", extraPrice: 200 },
      { attribute: "Brand", value: "Standard", extraPrice: 0 },
    ],
    images: ["img1", "img2"],
    recurringPlan: {
      name: "Starter Monthly",
      billingPeriod: "MONTHLY",
      price: 499,
      minimumQuantity: 1,
      autoClose: false,
      closeable: true,
      renewable: true,
      pausable: false,
    },
  },
  {
    id: "3",
    name: "Priority Support",
    category: "Support",
    type: "SERVICE",
    description:
      "24/7 dedicated support with guaranteed response times. Includes a dedicated account manager and escalation SLAs.",
    salesPrice: 299,
    monthlyPrice: 299,
    yearlyPrice: 2990,
    costPrice: 100,
    rating: 4.9,
    tag: "New",
    taxRate: 15,
    variants: [],
    images: ["img1"],
    recurringPlan: {
      name: "Support Monthly",
      billingPeriod: "MONTHLY",
      price: 299,
      minimumQuantity: 1,
      autoClose: false,
      closeable: true,
      renewable: true,
      pausable: false,
    },
  },
  {
    id: "4",
    name: "Cloud Hosting",
    category: "Hosting",
    type: "CONSUMABLE",
    description:
      "Managed cloud hosting optimised for Subly workloads. Auto-scaling, daily backups, and 99.9% uptime SLA included.",
    salesPrice: 799,
    monthlyPrice: 799,
    yearlyPrice: 7990,
    costPrice: 300,
    rating: 4.6,
    tag: null,
    taxRate: 15,
    variants: [
      { attribute: "Region", value: "US", extraPrice: 0 },
      { attribute: "Region", value: "EU", extraPrice: 100 },
      { attribute: "Region", value: "Asia", extraPrice: 50 },
    ],
    images: ["img1", "img2", "img3"],
    recurringPlan: {
      name: "Hosting Monthly",
      billingPeriod: "MONTHLY",
      price: 799,
      minimumQuantity: 1,
      autoClose: false,
      closeable: true,
      renewable: true,
      pausable: true,
    },
  },
  {
    id: "5",
    name: "Analytics Add-on",
    category: "Add-ons",
    type: "SERVICE",
    description:
      "Advanced reporting and dashboards with custom KPIs, scheduled exports, and team-wide visibility.",
    salesPrice: 199,
    monthlyPrice: 199,
    yearlyPrice: 1990,
    costPrice: 50,
    rating: 4.3,
    tag: null,
    taxRate: 15,
    variants: [],
    images: ["img1"],
    recurringPlan: null,
  },
  {
    id: "6",
    name: "Enterprise Suite",
    category: "SaaS",
    type: "SERVICE",
    description:
      "Everything in Pro plus multi-tenant support, SSO, audit logs, SLA guarantees, and a dedicated success manager.",
    salesPrice: 2499,
    monthlyPrice: 2499,
    yearlyPrice: 24990,
    costPrice: 1000,
    rating: 4.9,
    tag: "Best Value",
    taxRate: 15,
    variants: [
      { attribute: "Brand", value: "Odoo", extraPrice: 560 },
      { attribute: "Brand", value: "Standard", extraPrice: 0 },
      { attribute: "Tier", value: "Platinum", extraPrice: 800 },
      { attribute: "Tier", value: "Gold", extraPrice: 400 },
    ],
    images: ["img1", "img2", "img3"],
    recurringPlan: {
      name: "Enterprise Monthly",
      billingPeriod: "MONTHLY",
      price: 2499,
      minimumQuantity: 1,
      autoClose: false,
      closeable: true,
      renewable: true,
      pausable: true,
    },
  },
];

export function getProduct(id: string) {
  return PRODUCTS.find((p) => p.id === id) ?? null;
}
